version: "3.6"
services: 
    app:
      build: .
      ports: 
        - 8000:8000
        - 9229:9229 # enables debugging in VS Code
      command: npm run dev
      env_file: .env
      depends_on:
        - db
    db:
      image: postgres:10.16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data
volumes:
  db-data: